AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    polyscale-demo

    SAM Template for polyscale-demo
    
Globals:
    Function:
        Timeout: 5

Resources:

    PolyScaleDemoFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: database/
            Handler: index.handler
            Runtime: nodejs16.x
            Events:
                PolyScaleDemoAPI:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /
                        Method: get

    PolyScaleServerlessDemoFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: database-serverless/
            Handler: index.handler
            Runtime: nodejs16.x
            Events:
                PolyScaleDemoAPI:
                    Type: Api 
                    Properties:
                        Path: /serverless/
                        Method: get


Outputs:

    PolyScaleDemoApi:
      Description: "API Gateway endpoint URL for Prod stage for PolyScale function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ \n https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/serverless/"

    PolyScaleDemoFunction:
      Description: "PolyScale Demo Function ARN"
      Value: !GetAtt PolyScaleDemoFunction.Arn

    PolyScaleServerlessDemoFunction:
      Description: "PolyScale Serverless Demo Function ARN"
      Value: !GetAtt PolyScaleServerlessDemoFunction.Arn
